// <auto-generated />
namespace MvcApplication2.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changevalidationperson : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changevalidationperson));
        
        string IMigrationMetadata.Id
        {
            get { return "201311111236498_change validation person"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
